config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "sessions#show"
  get '/presignup' => 'sessions#accounttype', as: :presignup

  get '/existingsignup' => 'sessions#choosefamily', as: :choosefamily
  post '/existingsignup' => 'sessions#choosemember'
  post "/editaccount" => 'sessions#edit', as: :editaccount
  patch '/updateaccount' => 'sessions#update'

  get '/edit' => 'sessions#editselfaccount', as: :edit
  post '/edit' => 'sessions#validatesself'

  get '/signup' => 'sessions#newaccount', as: :signup
  post '/signup' => 'sessions#createaccount'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  resources :sessions, only: [:edit, :update]
  resources :memories
  resources :people
  resources :families


end

app/models/person.rb
class Person < ApplicationRecord
  has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#" },
    :default_url => "/app/assets/images/main-bg-2.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :family
  has_many :tags, dependent: :delete_all
  has_many :memories, through: :tags, dependent: :delete_all
  has_secure_password

  validates :username, presence: true, uniqueness: true, :if => :username
  validates :password, presence: true, :if => :password
  validates :dob, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{self.first_name.capitalize} #{self.last_name.capitalize}"
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authorize
  def index
    @people = current_user.family.people.sort_by{|person| person.dob.strftime("%Y%m%d").to_i}
    @family = current_user.family
  end

  def new
    @person = Person.new()
  end

  def create
     @person = Person.new(person_params)
     @person.family_id = current_user.family.id
     @person.username = "#{@person.full_name} #{@person.dob}"
     @person.password = "password"
     if @person.valid?
       @person.save
       redirect_to @person
     else
       flash[:errors] = @person.errors.full_messages
       redirect_to new_person_path
     end
   end

  def show
    if Person.find_by_id(params[:id])
      @person = Person.find(params[:id])
    else
      render "people/_noaccess.html.erb"
    end
  end

  def edit
    if Person.find_by_id(params[:id])
      @person = Person.find(params[:id])
    else
      render "people/_noaccess.html.erb"
    end
  end

  def update
  @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      flash[:errors] = @person.errors.full_messages
      redirect_to edit_person_path(@person)
    end
  end

  def destroy
   @person = Person.find(params[:id])
   if @person == current_user
     @person.destroy
     session[:person_id] = nil
     redirect_to '/login'
   else
     @person.destroy
     redirect_to people_path
   end
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :bio, :dob, :dod, :image)
  end
end

app/views/people/_form.html.erb
<% if flash[:errors] %>
  <ul>
    <br/>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %><br/>


<body>
  <div class="bodypeople">
    <div class="formpeople">
<%= bootstrap_form_for @person, html: { multipart: true } do |f| %>


        <%= f.text_field :first_name %><br/>

        <%= f.text_field :last_name %><br/>

        <%= f.text_area :bio %><br/>

        <%= f.date_field :dob, label: "Birthday" %><br/>

        <%= f.date_field :dod, label: "Date of death" %><br/>

        <%= f.file_field :image %><br/>

        <%= f.submit %>
      <% end %>


</div>
</div>
</body>

app/views/people/edit.html.erb
<% if !current_user.family.people.include?(@person) %>
  <%= render 'noaccess' %>
<% else %>
  <h2> Edit <%= @person.full_name %> </h2>
  <%= render 'form' %>
  <br/>

<div class = "formpeople" id="deletebtn">
  <%= form_tag person_path(@person), method: 'delete', class: "form-inline" do %>
  <% if @person == current_user %>
    <%= submit_tag 'Delete Account', class: "btn btn-default" %>
  <% else %>
    <%= submit_tag 'Delete Person', class: "btn btn-default" %>
  <% end %>
  <% end %>

</div>

<% end %>

app/views/people/index.html.erb
<h2> The <%= @family.family_name.capitalize %> Family Tree </h2>
<div class="hc-edit-family"><%= link_to "Edit Family", edit_family_path(current_user.family)  %></div>

<div class="hc-people-container">
  <% @people.each do |person| %>
    <div>
      <div class="hc-person-img">
        <% if person.image.url != "/app/assets/images/main-bg-2.jpg"%>
          <%= link_to image_tag(person.image.url(:medium)), person %>
        <% elsif person.image_url && person.image_url.strip != "" %>
          <%= link_to image_tag(person.image_url), person %>
          <% else %>
            <%= link_to image_tag("/assets/main-bg-2.jpg"), person %>
        <% end %>
      </div>
      <div class="hc-person-name">
        <%= person.full_name %>
      </div>

    </div>
  <% end %>
</div>

app/views/people/new.html.erb
<h2> Add New Family Member </h2>
<%= render 'form' %>

app/views/people/show.html.erb
<% if !current_user.family.people.include?(@person) %>
  <%= render 'noaccess.html.erb' %>
<% else %>

<!DOCTYPE html>
<html lang="en">
<head>
  <title> <%=  @person.first_name %> <%= @person.last_name %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>


<div class="container-fluid">
  <h2> <%=  @person.full_name%> </h2>
  
  <% if @person.image.url != "/app/assets/images/main-bg-2.jpg"%>
    <center><img src= <%= @person.image.url (:large)%>  alt="" class="img-rounded"></center>
  <% elsif @person.image_url && @person.image_url.strip != "" %>
    <center><img src= <%= @person.image_url%> alt="" class="img-rounded"></center>
  <% else %>
    <center><img src= "/assets/main-bg-2.jpg" alt="" class="img-rounded"></center>
  <% end %>


  <p>
    <ul>
      <center>
        <div class="bio">
          <label>Biography: </label>  <%= @person.bio %></br></br>
          <label>Date of Birth: </label>  <%= @person.dob %></br></br>
          <% if @person.dod %>
            <label>Date of Death: </label>  <%= @person.dod %></br></br>
          <% end  %>
        </div>


        <% if !@person.is_account %>
          <button type="button" class="btn btn-link"><%= link_to("Edit Person", edit_person_path )%></button>
        <% end %>


        <button type="button" class="btn btn-link"><%= link_to("All Family Members", people_path) %></button>

      </center>
    </ul>
  </p>





</div>




  <% if @person.memories.any? %>
    <h2>Memories</h2>

    <div class="row">
    <% @person.memories.each_with_index do |memory, index| %>


        <% if index % 3 == 0 %>
          <div class="col-md-4">
            <div class="img-fluid" alt="Responsive image">
              <% if memory.image.url != "/app/assets/images/missing_memory.jpg" %>
                <%= image_tag(memory.image.url(:medium)) %>
              <% elsif memory.image_url && memory.image_url.strip != "" %>
                <%=  image_tag(memory.image_url) %>
              <% else %>
                <%= image_tag("/assets/missing_memory.jpg") %>
              <% end %>
              <div class="captionks">
                <p> <%= link_to memory.title, memory %></p>
              </div>
            </div>
          </div>
        <% elsif index % 3 == 1%>

          <div class="col-md-4">
            <div class="img-fluid" alt="Responsive image">
              <% if memory.image.url != "/app/assets/images/missing_memory.jpg" %>
                <%= image_tag(memory.image.url(:medium)) %>
              <% elsif memory.image_url && memory.image_url.strip != "" %>
                <%=  image_tag(memory.image_url) %>
              <% else %>
                <%= image_tag("/assets/missing_memory.jpg") %>
              <% end %>

              <div class="captionks">
                <p> <%= link_to memory.title, memory %></p>
              </div>
            </div>
          </div>

        <% else %>

                  <div class="col-md-4">
                  <div class="img-fluid" alt="Responsive image">
                    <% if memory.image.url != "/app/assets/images/missing_memory.jpg" %>
                      <%= image_tag(memory.image.url(:medium)) %>
                    <% elsif memory.image_url && memory.image_url.strip != "" %>
                      <%=  image_tag(memory.image_url) %>
                    <% else %>
                      <%= image_tag("/assets/missing_memory.jpg") %>
                    <% end %>
                      <div class="captionks">
                        <p> <%= link_to memory.title, memory %></p>
                      </div>

                  </div>
                </div>









    <% end %>
  <% end %>

</div>

<% end %>

















</body>


<% end %>

</html>