config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "sessions#show"
  get '/presignup' => 'sessions#accounttype', as: :presignup

  get '/existingsignup' => 'sessions#choosefamily', as: :choosefamily
  post '/existingsignup' => 'sessions#choosemember'
  post "/editaccount" => 'sessions#edit', as: :editaccount
  patch '/updateaccount' => 'sessions#update'

  get '/edit' => 'sessions#editselfaccount', as: :edit
  post '/edit' => 'sessions#validatesself'

  get '/signup' => 'sessions#newaccount', as: :signup
  post '/signup' => 'sessions#createaccount'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  resources :sessions, only: [:edit, :update]
  resources :memories
  resources :people
  resources :families


end

app/models/family.rb
class Family < ApplicationRecord
    has_many :people
    has_many :memories
    has_secure_password

    validates :family_name, presence: true

    def family_name_and_id
      "#{self.id}. #{self.family_name.capitalize}"
    end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
before_action :authorize, only: [:show, :edit, :update]

  def new
    @family = Family.new
  end

  def create
    @family = Family.create(family_account_params)
    if @family.save
      redirect_to signup_path
    else
      flash[:errors] = @family.errors.full_messages
      redirect_to new_family_path
    end
  end

  def show
    @family = current_user.family
  end

  def edit
    @family = Family.find(params[:id])
  end

  def update
    @family = current_user.family
    @family.update(family_params)
    if @family.valid?
      redirect_to people_path
    else
      flash[:errors] = @family.errors.full_messages
      redirect_to edit_family_path
    end
  end

  private

  def family_account_params
    params.require(:family).permit(:family_name, :password, :password_confirmation)
  end

  def family_params
    params.require(:family).permit(:family_name)
  end




end

app/views/families/edit.html.erb
<% if current_user.family != @family %>
  <%= render 'noaccess' %>
<% else %>
  <% if flash[:errors] %>
    <ul>
      <br/>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %><br/>

  <h2>Edit <%= @family.family_name.capitalize %> Family</h2>
<center>
    <div class="formeditfamily">

  <%= form_for @family do |f| %>
    <%= f.label :family_name, label: "Family Name" %><br/>
    <%= f.text_field :family_name %><br/><br>
    <%= f.submit "Submit" %>
      <br/><br/>
  <% end %>
  </div>
</center>
<% end %>

app/views/families/new.html.erb
<% if flash[:errors] %>
  <ul>
    <br/>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %><br/>

<h2>New Family</h2>
<body>
  <div class="bodyfamily">
    <div class="formfamily">
<%= bootstrap_form_for @family do |f| %>

  <%= f.text_field :family_name %><br/>

  <%= f.password_field :password, label: "Family Password" %><br/>

  <%= f.password_field :password_confirmation %><br/>
  <center><%= f.submit "Submit" %></center>
  <br/>
  <br/>

<% end %>

</div>
</div>
</body>

app/views/families/show.html.erb
FAMILY SHOW!!!TIME


<br/><br/><br/><br/>
<%= link_to "View All Family Members", people_path %><br/>
<%= link_to "View All Memories", memories_path %><br/>

<br/><br/><br/><br/>
<%= link_to "Add New Family Member", new_person_path %><br/>
<%= link_to "Add New Memory", new_memory_path %><br/>